# Responses
DATA = "data"
ERRORS = "errors"
VALID = "valid"
MESSAGE = "message"
ERROR_TYPE = "type"

VALIDATION_ERROR = "ValidationError"
HTTP_400 = "Http400"
HTTP_404 = "Http404"
INTEGRITY_ERROR = "IntegrityError"
OTHER = "Other"
FIELD_ERROR = "FieldError"
INVALID_DATA = "InvalidData"
UNAUTHORIZED = "Unauthorized"
EMAIL_ERROR = "EmailError"
