# Generated by Django 4.1.13 on 2023-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlogger",
            name="object_id",
            field=models.TextField(blank=True, verbose_name="Object id"),
        ),
    ]
